items:
  mage-materia:
    material: fire_charge
    name: '&e[✦] Магическая материя'
    lore:
      - ''
      - ' &eВыдает игрокам в радиусе &a&l10 &eблоков'
      - ' &eэффекты &c&lЛевитации &eи &c&lСлепоты'
      - ''
    cooldown:
      time: 60 # В секундах.
      message: '&cПодождите еще &6{time} сек. &cперед использованием.'
    settings:
      glow: true
      radius:
        blocks: 10
        not-players: '&cРядом нет игроков, предмет не был использован.'
      effects:
        - 'LEVITATION 1 5' # Эффект Уровень Время(В секундах).
        - 'BLINDNESS 1 5'
      message: '&eПредмет &6&lМагическая материя &eбыл использован.'
  holy-angel:
    material: gunpowder
    name: '&d[✦] Святой ангел'
    lore:
      - ''
      - ' &eВыдает игрокам в радиусе &a&l10 &eблоков'
      - ' &eэффекты &c&lСвечения &eи &c&lМедлительности'
      - ''
    cooldown:
      time: 60 # В секундах.
      message: '&cПодождите еще &6{time} сек. &cперед использованием.'
    settings:
      glow: true
      radius:
        blocks: 10
        not-players: '&cРядом нет игроков, предмет не был использован.'
      effects:
        - 'GLOWING 1 60' # Эффект Уровень Время(В секундах).
        - 'SLOW 1 60'
      message: '&eПредмет &6&lСвятой ангел &eбыл использован.'
  speed-teleport:
    material: ender_pearl
    name: '&a[✦] Мгновенный телепорт'
    lore:
      - ''
      - ' &eТелепортирует вас туда, куда вы смотрите'
      - ''
    cooldown:
      time: 60 # В секундах.
      message: '&cПодождите еще &6{time} сек. &cперед использованием.'
    settings:
      glow: true
      max-distance: 100
      message: '&eПредмет &6&lМгновенный телепорт &eбыл использован.'

messages:
  no-permission: '&cУ вас недостаточно прав.'
  no-arg: '&cТакого аргумента не существует.'
  help:
    - ''
    - ' &c/{label} give <Игрок> <ID> <Кол-во> &7- Выдать предмет игроку.'
    - ' &c/{label} reload &7- Перезагрузить конфиги.'
    - ''

commands:
  give:
    usage: '&eИспользование: &c/{label} give <Игрок> <ID> <Кол-во>'
    success: '&aПредмет &6{ID} &aвыдан игроку &e{target} &7[&cx{amount}&7]'
    no-player: '&cТакого игрока нет на сервере.'
    no-id: '&cТакого предмета нет в конфиге.'
    no-int: '&cВы ввели недопустимое значение.'
    no-zero: '&cЧисло не должно быть меньше или равно 0.'
    full-inv: '&cНевозможно выдать, т. к инвентарь забит.'
  reload:
    success: '&aКонфиги перезагружены.'